# Generated by Django 5.2.6 on 2025-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
